"""update sensordata again table

Revision ID: 08cc7ae13724
Revises: f1c6948cff3b
Create Date: 2025-05-14 20:42:25.808849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cc7ae13724'
down_revision: Union[str, None] = 'f1c6948cff3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('Air_humidity_', sa.Float(), nullable=True))
    op.drop_column('sensordata', 'Air_humidity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('Air_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sensordata', 'Air_humidity_')
    # ### end Alembic commands ###
