"""update sensordata again

Revision ID: 763fab55463f
Revises: 08cc7ae13724
Create Date: 2025-05-14 21:02:15.696167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763fab55463f'
down_revision: Union[str, None] = '08cc7ae13724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('Air_temperature_C', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Pressure_KPa', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Soil_Humidity', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Soil_Moisture', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Wind_speed_Kmh', sa.Float(), nullable=True))
    op.drop_column('sensordata', 'Wind_speed_kmh')
    op.drop_column('sensordata', 'Soil_moisture')
    op.drop_column('sensordata', 'Air_temperature_c')
    op.drop_column('sensordata', 'Pressure_kpa')
    op.drop_column('sensordata', 'Soil_humidity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('Soil_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('Pressure_kpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('Air_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('Soil_moisture', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('Wind_speed_kmh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sensordata', 'Wind_speed_Kmh')
    op.drop_column('sensordata', 'Soil_Moisture')
    op.drop_column('sensordata', 'Soil_Humidity')
    op.drop_column('sensordata', 'Pressure_KPa')
    op.drop_column('sensordata', 'Air_temperature_C')
    # ### end Alembic commands ###
