"""update sensordata table

Revision ID: f1c6948cff3b
Revises: 5f080fd4088a
Create Date: 2025-05-14 20:40:37.795056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c6948cff3b'
down_revision: Union[str, None] = '5f080fd4088a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('Air_humidity', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Air_temperature_c', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Pressure_kpa', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Soil_humidity', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Soil_moisture', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Temperature', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Time', sa.Float(), nullable=True))
    op.add_column('sensordata', sa.Column('Wind_speed_kmh', sa.Float(), nullable=True))
    op.drop_column('sensordata', 'soil_moisture')
    op.drop_column('sensordata', 'soil_humidity')
    op.drop_column('sensordata', 'air_humidity')
    op.drop_column('sensordata', 'wind_speed_kmh')
    op.drop_column('sensordata', 'pressure_kpa')
    op.drop_column('sensordata', 'temperature')
    op.drop_column('sensordata', 'air_temperature_c')
    op.drop_column('sensordata', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('air_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('pressure_kpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('wind_speed_kmh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('air_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('soil_humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensordata', sa.Column('soil_moisture', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sensordata', 'Wind_speed_kmh')
    op.drop_column('sensordata', 'Time')
    op.drop_column('sensordata', 'Temperature')
    op.drop_column('sensordata', 'Soil_moisture')
    op.drop_column('sensordata', 'Soil_humidity')
    op.drop_column('sensordata', 'Pressure_kpa')
    op.drop_column('sensordata', 'Air_temperature_c')
    op.drop_column('sensordata', 'Air_humidity')
    # ### end Alembic commands ###
